### ISSUE TITLE
Add Yomitan attribution

### ISSUE THREAD

**Issue by Kuuuube** [Ajatt-Tools/rikaitan#101]
Due to the method used in updating the rikaitan repo, all attribution is stripped from commits. I think it is important to be transparent about the source of these commits. 

Especially given the strong promotion of open source software in  AJATT and Tatsumoto. The current state of the rikaitan repo is somewhat of a black box where commits cannot reasonably audited or looked over by users due to the enormous size. This is not something typical of "friendly" free projects. Pointing users to the upstream where they can view the full history is a good idea and should help alleviate this issue to some extent.

The easiest way to do this would be to simply add a note in the readme mentioning the upstream source of these commits. I have opened a PR for this.

**Comment by tatsumoto-ren** [comment]
People can simply submit their code directly to this repository instead. This is the easiest way. Unfortunately, some developers still haven't moved here, but I think we can wait for them to catch up.

But I agree, the way we pull commits from some Yomichan forks is not ideal at the moment. I guess we could rebase each commit at a time instead. We need to address this in the future.

The fork you mentioned can't be trusted because it is controlled by an organization that has a history of being a bad actor in the Japanese learning world. We can't allow our users find out about it because there's too much risk involved, so we can't add any links that point to it or mention it in any way. One of the reason rikaitan exists is to resist the takeover of the Yomichan development process by a hostile party. At least one trusted Yomichan fork is something that I think the users are in desperate need for.

I once [suggested](https://github.com/themoeway/yomitan/commit/defd3b6c5332f1f1bc294f06da7a03db4c5688c1#commitcomment-105626142) that a neutral organization would be a better candidate to manage the project. It can be Ajatt-Tools or anybody else as long as they're friendly to all parties and there's no proprietary software involved (since we've also observed that the repository you mentioned promotes malicious proprietary software). Currently we're doing it because it seems no one else is interested.

**Comment by Kuuuube** [comment]
Thank you for the response. I did not realize TMW was seen this way. I've closed my PR on this. 

Merging each commit in would be nice. I think you should be able to rebase all at once without conflicts until there is major development happening on this rikaitan.

**Comment by ganqqwerty** [comment]
It's still their code and until you add attribution in some way, you're violating the GPL3 license.
